# Generated by Django 3.2.7 on 2021-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь пишем наименование растворителя', max_length=30)),
                ('purpose', models.CharField(help_text='Здесь пишем назначение растворителя', max_length=50)),
                ('price', models.CharField(help_text='Здесь пишем цену растворителя', max_length=20)),
                ('currency', models.CharField(help_text='Здесь пишем валюту растворителя', max_length=20)),
                ('description', models.TextField(help_text='Здесь пишем комментарий')),
                ('country', models.CharField(help_text='Здесь пишем страну производства растворителя', max_length=50)),
            ],
        ),
    ]
