# Generated by Django 3.2.7 on 2021-09-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Im',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, db_index=True, upload_to='static/photo/', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='thinners',
            name='country',
            field=models.CharField(help_text='Здесь пишем страну производства растворителя', max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='thinners',
            name='currency',
            field=models.CharField(help_text='Здесь пишем валюту растворителя', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='thinners',
            name='description',
            field=models.TextField(help_text='Здесь пишем комментарий', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='thinners',
            name='name',
            field=models.CharField(help_text='Здесь пишем наименование растворителя', max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='thinners',
            name='price',
            field=models.CharField(help_text='Здесь пишем цену растворителя', max_length=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='thinners',
            name='purpose',
            field=models.CharField(help_text='Здесь пишем назначение растворителя', max_length=50, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='thinners',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.im'),
        ),
    ]
