# Generated by Django 3.2.7 on 2021-09-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ukr_thinners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukr_thinners',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.im'),
        ),
    ]
