# Generated by Django 3.2.7 on 2021-09-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_ukr_thinners_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='Здесь пишем заголовок новости', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Здесь пишем новость', verbose_name='Текст новости')),
                ('picture', models.ImageField(blank=True, db_index=True, upload_to='static/photo/%Y/%m/%d/', verbose_name='Фото к новости')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Здесь у нас дата опубликования новости', verbose_name='Дата опубликования')),
            ],
        ),
        migrations.AlterField(
            model_name='thinners',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.im'),
        ),
    ]
