# Generated by Django 3.2.7 on 2021-10-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210930_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Растворитель иностранный')),
                ('ukr_name', models.CharField(max_length=30, verbose_name='Растворитель украинский')),
                ('purpose', models.CharField(max_length=50, verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Дополнительная информация')),
            ],
        ),
    ]
