# Generated by Django 3.2.7 on 2021-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Растворитель иностранный'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ukr_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Растворитель украинский'),
        ),
    ]
