# Generated by Django 3.2.7 on 2021-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20211005_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Здесь у нас дата опубликования новости', verbose_name='Дата опубликования'),
        ),
    ]
