# Generated by Django 3.2.7 on 2021-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='Напишите Ваше имя, фамилию, и название организации')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона, пожалуйста')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
            ],
        ),
    ]
